version: '3'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server1:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - kafka-net    
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  #kafka-server2:
  #  image: 'bitnami/kafka:latest'
  #  container_name: consumer
  #  networks:
  #    - kafka-net    
  #  ports:
  #    - '9093:9092'
  #  environment:
  #    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
  #    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
  #    - ALLOW_PLAINTEXT_LISTENER=yes
  #  depends_on:
  #    - zookeeper-server